name: TraderRedux
main: me.killerkoda13.OmniExperienceTrader.OmniExperienceTrader
version: 0.0.1
description: Traders redone
load: POSTWORLD
# depend: [Multiverse-Core]
commands:
   xptrader:
      description: xptrader base command
      usage: /<command>
   xpt:
      description: xptrader base command
      usage: /<command>
