name: TraderRedux
main: me.killerkoda13.OmniExperienceTrader.OmniExperienceTrader
version: 0.0.1
description: Traders redone
commands:
   xptrader:
      description: Better Vanish
      usage: /<command>

